name: Bump Version
on:
  push:
    branches: [main]
    
permissions:
  contents: write
  
jobs:
  bump:
    runs-on: ubuntu-latest
    if: "startsWith(github.event.head_commit.message, '(build)')"
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          npm version patch -m "chore: bump version to %s"
          git push --follow-tags
